spring.application.name=devmemory-BE

# postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/devmemory
spring.datasource.username=devmemory
spring.datasource.password=devmemory
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
app.cors.allowed.origins=http://localhost:4200, https://app.devmemory.me
app.oauth2.success-redirect=http://localhost:4200

spring.security.oauth2.client.registration.google.client-id=157985843121-p4otg4bhma78tvi2i5hkpd5v5vpn83be.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email