spring.application.name=devmemory-BE
server.port=${SERVER_PORT:8080}

# postgres Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=Lax
server.servlet.session.cookie.http-only=true

# Server Configuration
app.cors.allowed.origins=http://localhost:4200, https://app.devmemory.me
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
app.oauth2.success-redirect=https://app.devmemory.me/