spring.application.name=devmemory-BE

# postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/devmemory
spring.datasource.username=devmemory
spring.datasource.password=devmemory
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
app.cors.allowed.origins=http://localhost:4200, https://app.devmemory.me

app.dev.single-user-id=00000000-0000-0000-0000-000000000001

spring.security.oauth2.client.registration.google.client-id=YOUR_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email